adviceCrud.titulo=Hype Advice - Cadastro
adviceList.titulo=Hype Advice - Pesquisa

sucesso.cadastro=Conselho cadastrado com sucesso.
sucesso.busca=Conselhos localizados com sucesso.

erro.tipo.obrigatorio=O Tipo de Conselho é obrigatório.
erro.descricao.obrigatoria=A Descrição é obrigatória.
erro.id.obrigatorio=O ID é obrigatório para a busca.
erro.nao.encontrado=Recurso não encontrado.
